import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import * as pdfjsLib from 'pdfjs-dist';
import './style.css';
pdfjsLib.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.mjs',import.meta.url).toString();

const tools=[
 ['editor','PDF Editor','Edit, preview, annotate and export','violet','✎'],
 ['converter','PDF Converter','PDF pages to JPG/PNG','pink','⇄'],
 ['merge','Merge PDF','Combine multiple PDF files','blue','＋'],
 ['split','Split PDF','Extract selected pages','orange','✂'],
 ['filetopdf','File → PDF','JPG/PNG images to PDF','green','▣'],
 ['security','Security','Inspect and remove metadata','red','✓'],
 ['doctor','PDF Doctor','Check and rebuild PDFs','cyan','✚']
];
const legal={about:['About Us','Chanvika PDF Editor is a browser-first PDF workspace focused on simple, colorful and useful document tools.'],contact:['Contact','Add your official support email and business details here before launch.'],privacy:['Privacy Policy','Core supported tools are designed for local browser processing. Update this policy before launch if you add advertising, analytics, cookies or other third-party services.'],terms:['Terms of Use','Use the service lawfully and keep backups of important documents. Exact reconstruction of every PDF layout or font is not guaranteed.'],disclaimer:['Disclaimer','Users are responsible for checking exported documents. This project does not claim unsupported encryption or perfect PDF reconstruction.'],faq:['FAQ','Core tools process supported files in the browser. PDF files can contain complex fonts, scans and layouts, so perfect editing of every PDF is not guaranteed.']};
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function Drop({accept,multiple=false,onFiles,label='Drop files here or choose files'}){const r=useRef();return <div className="dropzone" onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('drag')}} onDragLeave={e=>e.currentTarget.classList.remove('drag')} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove('drag');onFiles([...e.dataTransfer.files])}} onClick={()=>r.current?.click()}><div className="drop-icon">↑</div><strong>{label}</strong><small>Drag & drop or tap to browse</small><input ref={r} hidden type="file" accept={accept} multiple={multiple} onChange={e=>onFiles([...e.target.files])}/></div>}
function Ad({done}){const[n,setN]=useState(3);useEffect(()=>{const t=setInterval(()=>setN(x=>x?x-1:0),1000);return()=>clearInterval(t)},[]);return <div className="overlay"><div className="admodal"><small>ADVERTISEMENT</small><div className="adspace">Your ad can appear here</div>{n?<button disabled>Continue after {n}s</button>:<button className="primary" onClick={done}>Continue</button>}</div></div>}
function Shell({title,desc,cls='violet',go,children}){return <section className={'page '+cls}><div className="sectionHead"><div><span className="eyebrow">CHANVIKA TOOL</span><h1>{title}</h1><p>{desc}</p></div><button className="ghost" onClick={()=>go('home')}>← Home</button></div><div className="toolbox">{children}</div></section>}
function Editor({go}){const[file,setFile]=useState(null),[pdf,setPdf]=useState(null),[page,setPage]=useState(1),[img,setImg]=useState(null),[text,setText]=useState(''),[msg,setMsg]=useState(''),[gate,setGate]=useState(false);const open=async fs=>{const f=fs[0];if(!f)return;if(f.type!=='application/pdf'){setMsg('Please choose a PDF.');return}try{const p=await pdfjsLib.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;setFile(f);setPdf(p);setPage(1);setMsg(`${p.numPages} page(s) loaded.`)}catch(e){setMsg('Could not open this PDF.')}};useEffect(()=>{(async()=>{if(!pdf)return;try{const p=await pdf.getPage(page),v=p.getViewport({scale:1.25}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;setImg(c.toDataURL('image/png'))}catch(e){}})()},[pdf,page]);const exportPdf=()=>setGate(true);const after=async()=>{setGate(false);try{const d=await PDFDocument.load(await file.arrayBuffer());if(text.trim()){const f=await d.embedFont(StandardFonts.Helvetica);d.getPage(0).drawText(text,{x:36,y:d.getPage(0).getHeight()-55,size:16,font:f,color:rgb(.2,.12,.4)})}dl(new Blob([await d.save()],{type:'application/pdf'}),'chanvika-edited.pdf');setMsg('PDF exported successfully.')}catch(e){setMsg('Export failed.')}};return <Shell title="PDF Editor" desc="Upload a PDF, preview pages, add text and export locally." go={go}><div className="editor"><aside className="sidebar"><button onClick={()=>setPage(Math.max(1,page-1))}>↑ Prev</button><div className="counter">{pdf?`${page}/${pdf.numPages}`:'—'}</div><button onClick={()=>setPage(pdf?Math.min(pdf.numPages,page+1):1)}>↓ Next</button><Drop accept="application/pdf" onFiles={open} label="Upload"/></aside><main className="viewer">{img?<img className="pdfcanvas" src={img} alt="PDF page"/>:<Drop accept="application/pdf" onFiles={open} label="Upload PDF to start"/>}</main><div className="panel"><h3>Tools</h3>{['Select','Highlight','Draw','Shape','Image','Whiteout','Watermark'].map(x=><button className="toolbtn" key={x} onClick={()=>setMsg(`${x} tool selected. More advanced placement tools can be added to the editor engine.`)}>{x}</button>)}<label>Add text to first page</label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Type text…"/><button className="primary full" disabled={!file} onClick={exportPdf}>Save / Export PDF</button></div></div><div className="below"><Drop accept="application/pdf" onFiles={open} label="Choose / replace PDF"/>{msg&&<div className="notice">{msg}</div>}</div>{gate&&<Ad done={after}/>}</Shell>}
function FileList({files,remove}){return <div className="filelist">{files.map((f,i)=><div key={f.name+i}><span>{i+1}. {f.name}</span>{remove&&<button onClick={()=>remove(i)}>×</button>}</div>)}</div>}
function Merge({go}){const[files,setFiles]=useState([]),[msg,setMsg]=useState('');const run=async()=>{if(files.length<2){setMsg('Select at least 2 PDFs.');return}try{const out=await PDFDocument.create();for(const f of files){const d=await PDFDocument.load(await f.arrayBuffer());(await out.copyPages(d,d.getPageIndices())).forEach(p=>out.addPage(p))}dl(new Blob([await out.save()],{type:'application/pdf'}),'merged.pdf');setMsg('Merged PDF downloaded.')}catch(e){setMsg('Merge failed.')}};return <Shell title="Merge PDF" desc="Combine multiple PDF files into one." cls="blue" go={go}><Drop accept="application/pdf" multiple onFiles={fs=>setFiles(fs.filter(f=>f.type==='application/pdf'))}/><FileList files={files} remove={i=>setFiles(files.filter((_,x)=>x!==i))}/><button className="primary" disabled={!files.length} onClick={run}>Merge PDFs</button>{msg&&<div className="notice">{msg}</div>}</Shell>}
function parsePages(s,total){const a=new Set();for(const part of s.split(',')){let t=part.trim();if(!t)continue;if(t.includes('-')){let[x,y]=t.split('-').map(Number);if(x>y)[x,y]=[y,x];for(let n=x;n<=y;n++)if(n>=1&&n<=total)a.add(n)}else{let n=Number(t);if(n>=1&&n<=total)a.add(n)}}return [...a].sort((x,y)=>x-y)}
function Split({go}){const[file,setFile]=useState(null),[pages,setPages]=useState('1'),[msg,setMsg]=useState('');const run=async()=>{try{const d=await PDFDocument.load(await file.arrayBuffer()),out=await PDFDocument.create(),nums=parsePages(pages,d.getPageCount());if(!nums.length){setMsg('Enter pages like 1,3-5.');return}(await out.copyPages(d,nums.map(n=>n-1))).forEach(p=>out.addPage(p));dl(new Blob([await out.save()],{type:'application/pdf'}),'split-pages.pdf');setMsg('Selected pages downloaded.')}catch(e){setMsg('Split failed.')}};return <Shell title="Split PDF" desc="Extract selected pages into a new PDF." cls="orange" go={go}><Drop accept="application/pdf" onFiles={fs=>setFile(fs[0])}/><div className="field"><label>Pages</label><input value={pages} onChange={e=>setPages(e.target.value)} placeholder="1,3-5"/></div><button className="primary" disabled={!file} onClick={run}>Extract Pages</button>{msg&&<div className="notice">{msg}</div>}</Shell>}
function Converter({go}){const[file,setFile]=useState(null),[msg,setMsg]=useState('');const run=async()=>{try{const p=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;for(let i=1;i<=p.numPages;i++){const pg=await p.getPage(i),v=pg.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await pg.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const b=await new Promise(r=>c.toBlob(r,'image/jpeg',.9));dl(b,`page-${i}.jpg`)}setMsg(`Exported ${p.numPages} JPG page(s).`)}catch(e){setMsg('Conversion failed.')}};return <Shell title="PDF Converter" desc="Convert PDF pages to JPG directly in your browser." cls="pink" go={go}><Drop accept="application/pdf" onFiles={fs=>setFile(fs[0])}/><button className="primary" disabled={!file} onClick={run}>PDF → JPG</button><p className="hint">High-fidelity PDF↔Word/Excel/PPT conversion is not faked; it needs a compatible conversion engine.</p>{msg&&<div className="notice">{msg}</div>}</Shell>}
function FileToPdf({go}){const[files,setFiles]=useState([]),[msg,setMsg]=useState('');const run=async()=>{try{const out=await PDFDocument.create();for(const f of files){const b=await f.arrayBuffer(),im=f.type==='image/png'?await out.embedPng(b):await out.embedJpg(b),p=out.addPage([im.width,im.height]);p.drawImage(im,{x:0,y:0,width:im.width,height:im.height})}dl(new Blob([await out.save()],{type:'application/pdf'}),'images-to-pdf.pdf');setMsg('PDF created.')}catch(e){setMsg('Could not create PDF.')}};return <Shell title="File → PDF" desc="Turn JPG and PNG images into a PDF." cls="green" go={go}><Drop accept="image/jpeg,image/png" multiple onFiles={setFiles}/><FileList files={files}/><button className="primary" disabled={!files.length} onClick={run}>Create PDF</button>{msg&&<div className="notice">{msg}</div>}</Shell>}
function Security({go}){const[file,setFile]=useState(null),[info,setInfo]=useState('');const inspect=async()=>{try{const d=await PDFDocument.load(await file.arrayBuffer());setInfo(`Pages: ${d.getPageCount()} • Title: ${d.getTitle()||'Not set'} • Author: ${d.getAuthor()||'Not set'}`)}catch(e){setInfo('Could not inspect PDF.')}};const clean=async()=>{try{const d=await PDFDocument.load(await file.arrayBuffer());d.setTitle('');d.setAuthor('');d.setSubject('');d.setKeywords([]);dl(new Blob([await d.save()],{type:'application/pdf'}),'cleaned-pdf.pdf');setInfo('Cleaned PDF downloaded.')}catch(e){setInfo('Cleaning failed.')}};return <Shell title="Security" desc="Inspect and remove common document metadata." cls="red" go={go}><Drop accept="application/pdf" onFiles={fs=>setFile(fs[0])}/><div className="actions"><button className="primary" disabled={!file} onClick={inspect}>Inspect</button><button className="secondary" disabled={!file} onClick={clean}>Remove Metadata</button></div>{info&&<div className="info">{info}</div>}</Shell>}
function Doctor({go}){const[file,setFile]=useState(null),[msg,setMsg]=useState('');const check=async()=>{try{const d=await PDFDocument.load(await file.arrayBuffer());setMsg(`Readable PDF: ${d.getPageCount()} page(s).`)}catch(e){setMsg('PDF could not be parsed.')}};const rebuild=async()=>{try{const d=await PDFDocument.load(await file.arrayBuffer()),o=await PDFDocument.create();(await o.copyPages(d,d.getPageIndices())).forEach(p=>o.addPage(p));dl(new Blob([await o.save()],{type:'application/pdf'}),'repaired-pdf.pdf');setMsg('Rebuilt PDF downloaded.')}catch(e){setMsg('Rebuild failed.')}};return <Shell title="PDF Doctor" desc="Check readability and rebuild compatible PDFs." cls="cyan" go={go}><Drop accept="application/pdf" onFiles={fs=>setFile(fs[0])}/><div className="actions"><button className="primary" disabled={!file} onClick={check}>Check PDF</button><button className="secondary" disabled={!file} onClick={rebuild}>Rebuild / Optimize</button></div>{msg&&<div className="notice">{msg}</div>}</Shell>}
function Home({go}){return <main className="home"><section className="hero"><div><span className="eyebrow">ALL-IN-ONE PDF WORKSPACE</span><h1>Make every PDF<br/><em>work your way.</em></h1><p>Edit, merge, split, convert, clean and inspect PDFs with a colorful browser-first workflow.</p><button className="heroBtn" onClick={()=>go('editor')}>Open PDF Editor ✨</button></div><div className="heroVisual"><div className="paperCard"><b>PDF</b><span>Simple • Fast • Local</span></div><div className="bubble b1">✎ Edit</div><div className="bubble b2">＋ Merge</div><div className="bubble b3">⇄ Convert</div></div></section><section className="toolgrid">{tools.map(t=><button className={'toolcard '+t[3]} key={t[0]} onClick={()=>go(t[0])}><i>{t[4]}</i><strong>{t[1]}</strong><small>{t[2]}</small><b>→</b></button>)}</section><div className="adbanner">ADVERTISEMENT · Free tools supported by ads</div></main>}
function Legal({id,go}){return <section className="page"><span className="eyebrow">INFORMATION</span><h1>{legal[id][0]}</h1><div className="legalCard"><p>{legal[id][1]}</p>{id==='faq'&&<><h3>Are files uploaded?</h3><p>Core supported tools run in the browser.</p><h3>Can every PDF be edited perfectly?</h3><p>No. Complex PDFs may require specialized processing.</p></>}<button className="primary" onClick={()=>go('home')}>Back to Home</button></div></section>}
function App(){const[tab,setTab]=useState('home');useEffect(()=>{navigator.serviceWorker?.register('./sw.js').catch(()=>{})},[]);const go=x=>{setTab(x);scrollTo(0,0)};let c=tab==='home'?<Home go={go}/>:tab==='editor'?<Editor go={go}/>:tab==='merge'?<Merge go={go}/>:tab==='split'?<Split go={go}/>:tab==='converter'?<Converter go={go}/>:tab==='filetopdf'?<FileToPdf go={go}/>:tab==='security'?<Security go={go}/>:tab==='doctor'?<Doctor go={go}/>:legal[tab]?<Legal id={tab} go={go}/>:<Home go={go}/>;return <><header><button className="brand" onClick={()=>go('home')}><span>✦</span> Chanvika <b>PDF</b></button><nav>{tools.slice(0,4).map(t=><button key={t[0]} onClick={()=>go(t[0])}>{t[1]}</button>)}</nav><button className="headBtn" onClick={()=>go('editor')}>Start Editing →</button></header>{c}<footer><span>© 2026 Chanvika PDF Editor</span><div>{Object.keys(legal).map(k=><button key={k} onClick={()=>go(k)}>{legal[k][0]}</button>)}</div></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
